<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Introducing the ANCOVA - the analysis of covariance | An Introduction to Experimental Design and Linear Models</title>
  <meta name="description" content="This is an introduction to Experimental Design, ANOVA and ANCOVA analyses." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Introducing the ANCOVA - the analysis of covariance | An Introduction to Experimental Design and Linear Models" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is an introduction to Experimental Design, ANOVA and ANCOVA analyses." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Introducing the ANCOVA - the analysis of covariance | An Introduction to Experimental Design and Linear Models" />
  
  <meta name="twitter:description" content="This is an introduction to Experimental Design, ANOVA and ANCOVA analyses." />
  

<meta name="author" content="Andrew P Beckerman (based on text and slides from Mark Rees and Gareth Phoenix)" />


<meta name="date" content="2021-02-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="experimental-design-and-anova-a-summary.html"/>
<link rel="next" href="nonlinearities-polynomials-and-regression.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">And Introduction to Experimental Design and Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.0.1" data-path="index.html"><a href="index.html#the-three-rs"><i class="fa fa-check"></i><b>1.0.1</b> The Three Rs</a></li>
<li class="chapter" data-level="1.0.2" data-path="index.html"><a href="index.html#the-general-linear-model"><i class="fa fa-check"></i><b>1.0.2</b> The General Linear Model</a></li>
<li class="chapter" data-level="1.0.3" data-path="index.html"><a href="index.html#section-readings--"><i class="fa fa-check"></i><b>1.0.3</b> Section Readings —-</a></li>
<li class="chapter" data-level="1.0.4" data-path="index.html"><a href="index.html#install-some-extra-packages--"><i class="fa fa-check"></i><b>1.0.4</b> Install some extra packages —-</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction To Experiments (Some Philosophy)</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#how-to-think-about-experiments-components-of-an-experiment"><i class="fa fa-check"></i><b>2.1</b> How to think about experiments: Components of an Experiment</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="intro.html"><a href="intro.html#how-do-we-increase-precision-and-reduce-bias"><i class="fa fa-check"></i><b>2.1.1</b> How do we increase precision and reduce bias?</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#experimental-vs-measurement-units"><i class="fa fa-check"></i><b>2.2</b> Experimental vs Measurement units</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="intro.html"><a href="intro.html#take-home-message-randomization-properly-with-replication-protects-against-confounding"><i class="fa fa-check"></i><b>2.2.1</b> Take Home Message: Randomization properly with Replication protects against Confounding</a></li>
<li class="chapter" data-level="2.2.2" data-path="intro.html"><a href="intro.html#a-non-randomized-experiment-haphazard-is-not-randomized"><i class="fa fa-check"></i><b>2.2.2</b> A non-randomized experiment – <strong>haphazard</strong> is NOT randomized</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#mini-quiz"><i class="fa fa-check"></i><b>2.3</b> Mini-Quiz</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#replication-how-many"><i class="fa fa-check"></i><b>2.4</b> Replication: How many?</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="standard-errors-precision-and-sampling.html"><a href="standard-errors-precision-and-sampling.html"><i class="fa fa-check"></i><b>3</b> Standard Errors, Precision and Sampling</a>
<ul>
<li class="chapter" data-level="3.1" data-path="standard-errors-precision-and-sampling.html"><a href="standard-errors-precision-and-sampling.html#standard-errors-and-precision"><i class="fa fa-check"></i><b>3.1</b> Standard Errors and precision</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="standard-errors-precision-and-sampling.html"><a href="standard-errors-precision-and-sampling.html#se-of-a-difference-and-balance."><i class="fa fa-check"></i><b>3.1.1</b> SE of a Difference and Balance.</a></li>
<li class="chapter" data-level="3.1.2" data-path="standard-errors-precision-and-sampling.html"><a href="standard-errors-precision-and-sampling.html#however-sometimes-unbalanced-designs-are-better."><i class="fa fa-check"></i><b>3.1.2</b> However sometimes unbalanced designs are better.</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="standard-errors-precision-and-sampling.html"><a href="standard-errors-precision-and-sampling.html#the-crd-completely-randomised-design"><i class="fa fa-check"></i><b>3.2</b> The CRD: Completely Randomised Design</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="examples-and-challenge-questions.html"><a href="examples-and-challenge-questions.html"><i class="fa fa-check"></i><b>4</b> Examples and Challenge Questions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="examples-and-challenge-questions.html"><a href="examples-and-challenge-questions.html#designing-your-first-experiment"><i class="fa fa-check"></i><b>4.1</b> Designing your first experiment</a></li>
<li class="chapter" data-level="4.2" data-path="examples-and-challenge-questions.html"><a href="examples-and-challenge-questions.html#using-r-to-generate-experimental-designs"><i class="fa fa-check"></i><b>4.2</b> Using R to generate Experimental Designs</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="design-and-analysis-of-experiments.html"><a href="design-and-analysis-of-experiments.html"><i class="fa fa-check"></i><b>5</b> Design and Analysis of Experiments</a>
<ul>
<li class="chapter" data-level="5.1" data-path="design-and-analysis-of-experiments.html"><a href="design-and-analysis-of-experiments.html#example-one"><i class="fa fa-check"></i><b>5.1</b> Example one</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="design-and-analysis-of-experiments.html"><a href="design-and-analysis-of-experiments.html#making-up-data"><i class="fa fa-check"></i><b>5.1.1</b> Making up data</a></li>
<li class="chapter" data-level="5.1.2" data-path="design-and-analysis-of-experiments.html"><a href="design-and-analysis-of-experiments.html#into-the-dplyr-and-ggplot-pipeline."><i class="fa fa-check"></i><b>5.1.2</b> Into the dplyr and ggplot pipeline.</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="design-and-analysis-of-experiments.html"><a href="design-and-analysis-of-experiments.html#the-one-way-anova."><i class="fa fa-check"></i><b>5.2</b> The One-Way ANOVA.</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="design-and-analysis-of-experiments.html"><a href="design-and-analysis-of-experiments.html#making-insight-and-inference"><i class="fa fa-check"></i><b>5.2.1</b> Making insight and inference</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="design-and-analysis-of-experiments.html"><a href="design-and-analysis-of-experiments.html#a-priori-vs.-post-hoc-contrasts"><i class="fa fa-check"></i><b>5.3</b> A priori vs. Post-Hoc Contrasts</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="design-and-analysis-of-experiments.html"><a href="design-and-analysis-of-experiments.html#the-more-appropriate-approach."><i class="fa fa-check"></i><b>5.3.1</b> The more appropriate approach.</a></li>
<li class="chapter" data-level="5.3.2" data-path="design-and-analysis-of-experiments.html"><a href="design-and-analysis-of-experiments.html#comparing-the-average-of-the-herbicide-effect-with-the-control."><i class="fa fa-check"></i><b>5.3.2</b> comparing the average of the herbicide effect with the control.</a></li>
<li class="chapter" data-level="5.3.3" data-path="design-and-analysis-of-experiments.html"><a href="design-and-analysis-of-experiments.html#writing-this-up"><i class="fa fa-check"></i><b>5.3.3</b> writing this up…</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="randomized-complete-block-design-rcb.html"><a href="randomized-complete-block-design-rcb.html"><i class="fa fa-check"></i><b>6</b> Randomized Complete Block design (RCB)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="randomized-complete-block-design-rcb.html"><a href="randomized-complete-block-design-rcb.html#an-example-of-the-rcbd"><i class="fa fa-check"></i><b>6.1</b> An example of the RCBD</a></li>
<li class="chapter" data-level="6.2" data-path="randomized-complete-block-design-rcb.html"><a href="randomized-complete-block-design-rcb.html#analysing-the-crbd"><i class="fa fa-check"></i><b>6.2</b> Analysing the CRBD</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="randomized-complete-block-design-rcb.html"><a href="randomized-complete-block-design-rcb.html#building-the-model"><i class="fa fa-check"></i><b>6.2.1</b> Building the model</a></li>
<li class="chapter" data-level="6.2.2" data-path="randomized-complete-block-design-rcb.html"><a href="randomized-complete-block-design-rcb.html#are-the-estimates-of-the-parameters-what-we-expect"><i class="fa fa-check"></i><b>6.2.2</b> Are the estimates of the parameters what we expect?</a></li>
<li class="chapter" data-level="6.2.3" data-path="randomized-complete-block-design-rcb.html"><a href="randomized-complete-block-design-rcb.html#correct-standard-errors-for-a-figure"><i class="fa fa-check"></i><b>6.2.3</b> Correct Standard Errors for a Figure</a></li>
<li class="chapter" data-level="6.2.4" data-path="randomized-complete-block-design-rcb.html"><a href="randomized-complete-block-design-rcb.html#making-inference-confidence-intervals-and-contrasts"><i class="fa fa-check"></i><b>6.2.4</b> Making inference: confidence intervals and contrasts</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="the-latin-square-design-lsd.html"><a href="the-latin-square-design-lsd.html"><i class="fa fa-check"></i><b>7</b> The Latin Square Design (LSD)</a>
<ul>
<li class="chapter" data-level="7.0.1" data-path="the-latin-square-design-lsd.html"><a href="the-latin-square-design-lsd.html#fitting-the-model"><i class="fa fa-check"></i><b>7.0.1</b> Fitting the model</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="designs-for-testing-for-interactions-factorial-designs-.html"><a href="designs-for-testing-for-interactions-factorial-designs-.html"><i class="fa fa-check"></i><b>8</b> Designs for testing for interactions: factorial designs.</a>
<ul>
<li class="chapter" data-level="8.1" data-path="designs-for-testing-for-interactions-factorial-designs-.html"><a href="designs-for-testing-for-interactions-factorial-designs-.html#introducing-interactions"><i class="fa fa-check"></i><b>8.1</b> Introducing Interactions</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="designs-for-testing-for-interactions-factorial-designs-.html"><a href="designs-for-testing-for-interactions-factorial-designs-.html#lets-design-an-experiment-again"><i class="fa fa-check"></i><b>8.1.1</b> Let’s design an experiment, again…</a></li>
<li class="chapter" data-level="8.1.2" data-path="designs-for-testing-for-interactions-factorial-designs-.html"><a href="designs-for-testing-for-interactions-factorial-designs-.html#the-factorial-design-how-and-why-study-interactions"><i class="fa fa-check"></i><b>8.1.2</b> The Factorial Design: How and Why Study Interactions?</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="designs-for-testing-for-interactions-factorial-designs-.html"><a href="designs-for-testing-for-interactions-factorial-designs-.html#a-factorial-design-and-the-two-way-anova"><i class="fa fa-check"></i><b>8.2</b> A Factorial Design and the Two-Way ANOVA</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="designs-for-testing-for-interactions-factorial-designs-.html"><a href="designs-for-testing-for-interactions-factorial-designs-.html#build-the-data"><i class="fa fa-check"></i><b>8.2.1</b> Build the Data</a></li>
<li class="chapter" data-level="8.2.2" data-path="designs-for-testing-for-interactions-factorial-designs-.html"><a href="designs-for-testing-for-interactions-factorial-designs-.html#plot-the-data"><i class="fa fa-check"></i><b>8.2.2</b> Plot the data!</a></li>
<li class="chapter" data-level="8.2.3" data-path="designs-for-testing-for-interactions-factorial-designs-.html"><a href="designs-for-testing-for-interactions-factorial-designs-.html#analyse-the-data"><i class="fa fa-check"></i><b>8.2.3</b> Analyse the data</a></li>
<li class="chapter" data-level="8.2.4" data-path="designs-for-testing-for-interactions-factorial-designs-.html"><a href="designs-for-testing-for-interactions-factorial-designs-.html#final-figuring"><i class="fa fa-check"></i><b>8.2.4</b> final figuring</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="experimental-design-and-anova-a-summary.html"><a href="experimental-design-and-anova-a-summary.html"><i class="fa fa-check"></i><b>9</b> Experimental Design and ANOVA - A Summary</a>
<ul>
<li class="chapter" data-level="9.1" data-path="experimental-design-and-anova-a-summary.html"><a href="experimental-design-and-anova-a-summary.html#how-to-analyse-anova-models"><i class="fa fa-check"></i><b>9.1</b> How To Analyse ANOVA models</a></li>
<li class="chapter" data-level="9.2" data-path="experimental-design-and-anova-a-summary.html"><a href="experimental-design-and-anova-a-summary.html#experimental-designs."><i class="fa fa-check"></i><b>9.2</b> Experimental Designs.</a></li>
<li class="chapter" data-level="9.3" data-path="experimental-design-and-anova-a-summary.html"><a href="experimental-design-and-anova-a-summary.html#clever-r-stuff"><i class="fa fa-check"></i><b>9.3</b> Clever R Stuff</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html"><i class="fa fa-check"></i><b>10</b> Introducing the ANCOVA - the analysis of covariance</a>
<ul>
<li class="chapter" data-level="10.1" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html#setting-up-the-various-ideas."><i class="fa fa-check"></i><b>10.1</b> Setting up the various ideas.</a></li>
<li class="chapter" data-level="10.2" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html#working-through-and-example."><i class="fa fa-check"></i><b>10.2</b> Working through and example.</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html#get-the-data-and-make-your-picture"><i class="fa fa-check"></i><b>10.2.1</b> Get the data and make your picture</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html#building-the-model-and-understanding-it"><i class="fa fa-check"></i><b>10.3</b> Building the model (and understanding it)</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html#dealing-with-some-issues-with-residuals."><i class="fa fa-check"></i><b>10.3.1</b> Dealing with some issues with residuals.</a></li>
<li class="chapter" data-level="10.3.2" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html#making-inference-on-the-ancova"><i class="fa fa-check"></i><b>10.3.2</b> Making inference on the ANCOVA</a></li>
<li class="chapter" data-level="10.3.3" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html#the-summary-table-and-making-sense-of-the-log-stuff."><i class="fa fa-check"></i><b>10.3.3</b> The summary table and making sense of the log stuff.</a></li>
<li class="chapter" data-level="10.3.4" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html#the-equations-supported-by-the-model."><i class="fa fa-check"></i><b>10.3.4</b> The equations supported by the model.</a></li>
<li class="chapter" data-level="10.3.5" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html#making-even-more-inference-and-drawing-the-picture"><i class="fa fa-check"></i><b>10.3.5</b> Making even more inference and drawing the picture</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html#some-general-principles"><i class="fa fa-check"></i><b>10.4</b> Some General Principles</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html#ancova-always-tests-the-interaction-against-the-additive-model"><i class="fa fa-check"></i><b>10.4.1</b> ANCOVA always tests the interaction against the additive model</a></li>
<li class="chapter" data-level="10.4.2" data-path="introducing-the-ancova-the-analysis-of-covariance.html"><a href="introducing-the-ancova-the-analysis-of-covariance.html#specifying-models-in-r"><i class="fa fa-check"></i><b>10.4.2</b> Specifying models in R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html"><i class="fa fa-check"></i><b>11</b> Nonlinearities, polynomials and regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#transformations---a-reminder-and-starting-point."><i class="fa fa-check"></i><b>11.1</b> Transformations - a reminder and starting point.</a></li>
<li class="chapter" data-level="11.2" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#working-through-an-example."><i class="fa fa-check"></i><b>11.2</b> Working through an example.</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#interlude-1---inference-before-fixing-the-problem"><i class="fa fa-check"></i><b>11.2.1</b> Interlude 1 - Inference before fixing the problem</a></li>
<li class="chapter" data-level="11.2.2" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#solving-the-problem-i-the-non-linearity"><i class="fa fa-check"></i><b>11.2.2</b> Solving the Problem I: The Non-linearity</a></li>
<li class="chapter" data-level="11.2.3" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#interlude-2---inference-before-fixing-both-problems"><i class="fa fa-check"></i><b>11.2.3</b> Interlude 2 - Inference before fixing both problems</a></li>
<li class="chapter" data-level="11.2.4" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#solving-the-problem-ii-non-constant---increasing-variance"><i class="fa fa-check"></i><b>11.2.4</b> Solving the Problem II: Non-constant - increasing variance</a></li>
<li class="chapter" data-level="11.2.5" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#interlude-3---inference-with-both-things-corrected."><i class="fa fa-check"></i><b>11.2.5</b> Interlude 3 - Inference with both things corrected.</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#anova-tables-with-multiple-explantory-variables."><i class="fa fa-check"></i><b>11.3</b> Anova Tables with multiple explantory variables.</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#explaining-the-trick"><i class="fa fa-check"></i><b>11.3.1</b> Explaining the Trick</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#types-of-anova"><i class="fa fa-check"></i><b>11.4</b> Types of ANOVA</a></li>
<li class="chapter" data-level="11.5" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#explaining-the-result---a-dose-of-reality"><i class="fa fa-check"></i><b>11.5</b> Explaining the result - a dose of reality</a></li>
<li class="chapter" data-level="11.6" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#a-mechanistic-model"><i class="fa fa-check"></i><b>11.6</b> A mechanistic model</a></li>
<li class="chapter" data-level="11.7" data-path="nonlinearities-polynomials-and-regression.html"><a href="nonlinearities-polynomials-and-regression.html#the-take-home-messages"><i class="fa fa-check"></i><b>11.7</b> The Take Home Messages</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="a-final-overview.html"><a href="a-final-overview.html"><i class="fa fa-check"></i><b>12</b> A final Overview</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Introduction to Experimental Design and Linear Models</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introducing-the-ancova---the-analysis-of-covariance" class="section level1" number="10">
<h1><span class="header-section-number">Chapter 10</span> Introducing the ANCOVA - the analysis of covariance</h1>
<p>In the previous chapters, we introduced classic experimental design principles, and in doing so, we focused on revisiting the 1-way ANOVA and introduced the 2-way ANOVA. In these models, the explanatory variables are categorical (they are factors). This means explanatory variable has distinct, discrete categories or <em>levels</em>.</p>
<p>In many of our experiments, however, we might combine these categorical variables with a continuous variable. For example, we might estimate eggs produced as a function of body size and season or we might estimate the effect on plant growth rates of soil moisture in high versus low Nitrogen (N) conditions.</p>
<p>These simple examples describe an ANCOVA, where the one explanatory variable is continuous (e.g. body size or soil moisture) and the other is categorical (e.g. season or N-level). When this is the case, we are essentially combining the ANOVA with the Regression. If we recall that regression is largely about estimatinge slopes and intercepts, we might think, hey, COOL, so in an ANCOVA, we can ask if the categorical variable alters the slope or not…..</p>
<p>What’s very important to understand is that our core statement about interactions does not change.</p>
<blockquote>
<p>The effect of X on Y varies by Z, translates to a) The effect of body size on egg production varies by season; or b) the effect of soil moisture on growth rate varies by N-level</p>
</blockquote>
<p>When written like this, the previous statements about slopes should be even more clear. The effect of body size (continuous) on egg production is a regression and we estimate a slope. We then can ask whether this slope is different between seasons.</p>
<div id="setting-up-the-various-ideas." class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> Setting up the various ideas.</h2>
<p>Let’s start by looking at an example where the effect of Height on Weight varies by Sex. This is a classic set of data from numerous organisms…. it captures biologically the question about sexual dimorphism - does the relationship between Height and Weight (a regression) vary by Sex (ANOVA)?</p>
<p>This relationship can take on many patterns.</p>
<p><img src="images/ANCOVA_1.png" width="644" /></p>
<ul>
<li>In the upper left we see a pattern where Males are heavier than Females, but there is no effect of Height on Weight.</li>
<li>In the upper right, we see that there is a positive relationship between Weight and Height, but no differences between Males and Females.</li>
<li>In the lower left, we might argue that there is a positive relationship between Weight and Height, that the relationship between Weight and Height does not vary (the slope is the same) and that Males are heavier (the red dots are mostly above the blue)</li>
<li>In the lower right, we see evidence of an interaction - the effect of Height on Weight (the slopes), varies by Sex.</li>
</ul>
<p>It’s quite important to recognise that each of patterns is possible outcome to testing the SAMEa hypothesis. The key thing to remember is that we have an a priori (in advance hypothesis). Regardless of the pattern, we should specify the appropriate model to test your the hypothesis and answer the question that motivated the design of the experiment and data collection.</p>
<p>For example, in these data, we fundamentally start with the question - does the effect of Height on Weight vary by Sex. The data might look like any of the above patterns. But as we started with that, we have to try and answer that question. And there is only one model syntax in the above figure that does this: <code>Weight ~ Height * Sex</code>. We’ll expand on what this means as we work through the example.</p>
</div>
<div id="working-through-and-example." class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> Working through and example.</h2>
<p>Let’s work with a built in dataset in R - the Davis Study, which is exactly these data. The associated assignment is another example.</p>
<p>The process of doing this will follow a tried and true approach to analysing data. You should embed this workflow in your head:</p>
<ol style="list-style-type: decimal">
<li>PLOT the Data</li>
<li>Build the model to test the hypothesis</li>
<li>Check the Assumptions</li>
<li>Make Inference</li>
<li>Update the Figure for Publication</li>
</ol>
<div id="get-the-data-and-make-your-picture" class="section level3" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> Get the data and make your picture</h3>
<p>The data are built into R, but embedded in the <code>carData</code> package, which was installed with the <code>car</code> package.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb84-1" aria-hidden="true" tabindex="-1"></a>Davis <span class="ot">&lt;-</span> carData<span class="sc">::</span>Davis</span>
<span id="cb84-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb84-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-3"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(Davis)</span></code></pre></div>
<pre><code>## Rows: 200
## Columns: 5
## $ sex    &lt;fct&gt; M, F, F, M, F, M, M, M, M, M, M, F, F, F, F, F, M, F, M, F, M,…
## $ weight &lt;int&gt; 77, 58, 53, 68, 59, 76, 76, 69, 71, 65, 70, 166, 51, 64, 52, 6…
## $ height &lt;int&gt; 182, 161, 161, 177, 157, 170, 167, 186, 178, 171, 175, 57, 161…
## $ repwt  &lt;int&gt; 77, 51, 54, 70, 59, 76, 77, 73, 71, 64, 75, 56, 52, 64, 57, 66…
## $ repht  &lt;int&gt; 180, 159, 158, 175, 155, 165, 165, 180, 175, 170, 174, 163, 15…</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Davis, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight, <span class="at">col =</span> sex))<span class="sc">+</span></span>
<span id="cb86-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="Introduction-to-Experimental-Design-and-Analysis_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>Ahh…. first hurdle…. what’s going on here? Well, always plot your data is totally justified, because it looks like one of the data points has the Height and Weight data entered incorrectly.</p>
<p>Let’s fix that. Lets find the row, and make the change</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co">#which row? 12</span></span>
<span id="cb87-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb87-2" aria-hidden="true" tabindex="-1"></a>Davis <span class="sc">%&gt;%</span> <span class="fu">filter</span>(height <span class="sc">&lt;</span> <span class="dv">100</span>)</span></code></pre></div>
<pre><code>##    sex weight height repwt repht
## 12   F    166     57    56   163</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># BASE R syntax to see each observation</span></span>
<span id="cb89-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb89-2" aria-hidden="true" tabindex="-1"></a>Davis<span class="sc">$</span>weight[<span class="dv">12</span>]</span></code></pre></div>
<pre><code>## [1] 166</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb91-1" aria-hidden="true" tabindex="-1"></a>Davis<span class="sc">$</span>height[<span class="dv">12</span>]</span></code></pre></div>
<pre><code>## [1] 57</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># BASE R syntax to change them</span></span>
<span id="cb93-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb93-2" aria-hidden="true" tabindex="-1"></a>Davis<span class="sc">$</span>weight[<span class="dv">12</span>] <span class="ot">&lt;-</span> <span class="dv">57</span></span>
<span id="cb93-3"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb93-3" aria-hidden="true" tabindex="-1"></a>Davis<span class="sc">$</span>height[<span class="dv">12</span>] <span class="ot">&lt;-</span> <span class="dv">166</span></span>
<span id="cb93-4"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb93-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-5"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb93-5" aria-hidden="true" tabindex="-1"></a><span class="co"># replot</span></span>
<span id="cb93-6"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb93-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Davis, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight, <span class="at">col =</span> sex))<span class="sc">+</span></span>
<span id="cb93-7"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb93-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="Introduction-to-Experimental-Design-and-Analysis_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<p>Excellent. Lets look at this picture and ask ourselves whether the effect of Height on Weight appears to vary by Sex? What do you think?</p>
<p>We can actually get a bit of help here. We can use some ggplot magic to help us make this GUESS.
&gt; NOTE: this is not doing statistics. This is using graphics to help guide our expectation of the outcome of doing the statistical test of our hypothesis.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Davis, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight, <span class="at">col =</span> sex))<span class="sc">+</span></span>
<span id="cb94-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb94-3"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># add a best fit line to each group (the sex category)</span></span>
<span id="cb94-4"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb94-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="Introduction-to-Experimental-Design-and-Analysis_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<p>Again, we have not ‘proven’ anything or tested our hypothesis. What we have is a good guess though. We can guess that</p>
<ol style="list-style-type: decimal">
<li>Males are heavier than females (what is the difference in the intercepts?)</li>
<li>The effect of height on weight is positive (the slope(s) are positive, not negative)</li>
<li>There might be a difference in slopes - the Male line is steeper.</li>
</ol>
<p>We might even go as far to estimate by eye the slope assuming that there is no effect of Sex. Recalling that the slope is the rise/run or the change in y over the change in x, we can guess that the slope is ~ (100-40)/(200-140) = (60/60) = 1. We are not expecting much variation around that. But if we see the statistics returning a value 10x more or less than this, we should be concerned!</p>
</div>
</div>
<div id="building-the-model-and-understanding-it" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> Building the model (and understanding it)</h2>
<p>The next step is to build the model to test our hypothesis. As we declared above, the model to test the interaction is <code>lm(weight ~ height * sex, data = Davis)</code>. Let’s discuss this a bit.</p>
<p>First, this model expands to the following full description:</p>
<p><code>lm(weight ~ height + sex + height:sex, data = Davis)</code></p>
<p>This reads as "Weight is a function of the effect of Height (slope), Sex (intercept) and the interaction between Height and Sex (do the slopes vary?). The <code>Height * Sex</code> syntax always expands to this <em>full model</em> - the model containing the main effects and the interaction.</p>
<p>OK. Let’s fit the model</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we call the model mod_Davis.</span></span>
<span id="cb96-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb96-2" aria-hidden="true" tabindex="-1"></a>mod_Davis <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> height <span class="sc">+</span> sex <span class="sc">+</span> height<span class="sc">:</span>sex, <span class="at">data =</span> Davis)</span></code></pre></div>
<p>That’s it. We’ve got the model. But before we make any attempts at actually evaluating our test of the hypothesis, we have to check the assumptions!</p>
<p>To do this, we use the autplot function from the ggfortify package.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(mod_Davis)</span></code></pre></div>
<p><img src="Introduction-to-Experimental-Design-and-Analysis_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<p>OK. Let’s walk through the three core diagnostics.</p>
<p>In the upper left, we are evaluating the systematic part of the model - are there any systematic departures from the linear model we’ve speficied? Are there interactions missing or specific nonlinearities? Nope.</p>
<p>In the upper right, we are evaluating the normality of the residuals. These too look pretty good.</p>
<p>In the lower left, we are evalauting the assumption of a constant mean-variance relationship. Oops.</p>
<div id="dealing-with-some-issues-with-residuals." class="section level3" number="10.3.1">
<h3><span class="header-section-number">10.3.1</span> Dealing with some issues with residuals.</h3>
<p>The above issue is one we can deal with via a <em>transformation</em>. Let’s start with the facts…. When the variance increases with the mean, one transformation that can work is the logarithm of the continuous variables.</p>
<p>ADD DYLANS STUFF FROM MEE PAPERS and Mean - VARIANCE</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># re-plot with log-log</span></span>
<span id="cb98-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Davis, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">log</span>(height), <span class="at">y =</span> <span class="fu">log</span>(weight), <span class="at">col =</span> sex))<span class="sc">+</span></span>
<span id="cb98-3"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb98-4"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb98-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="Introduction-to-Experimental-Design-and-Analysis_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the model - note we can specify the transformation RIGHT IN THE MODEL</span></span>
<span id="cb100-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb100-2" aria-hidden="true" tabindex="-1"></a>mod_Davis_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(weight) <span class="sc">~</span> <span class="fu">log</span>(height) <span class="sc">*</span> sex, <span class="at">data =</span> Davis)</span>
<span id="cb100-3"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb100-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-4"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb100-4" aria-hidden="true" tabindex="-1"></a><span class="co"># check the new residuals</span></span>
<span id="cb100-5"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb100-5" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(mod_Davis_log)</span></code></pre></div>
<p><img src="Introduction-to-Experimental-Design-and-Analysis_files/figure-html/unnamed-chunk-53-2.png" width="672" /></p>
<p>This is definitely flatter - you can tell by the range on the y-axis of the scale-location plot.</p>
<p>So, we can now move to evaluating the model. You are probably thinking about what it means to analyse the data on the log-log axis…. we will come to that shortly.</p>
</div>
<div id="making-inference-on-the-ancova" class="section level3" number="10.3.2">
<h3><span class="header-section-number">10.3.2</span> Making inference on the ANCOVA</h3>
<p>OK. So, the next step is to use review the ANOVA table - yes, we use the same Anova function to build an anova table to explore the results of an ANCOVA.</p>
<p>Let’s revisit our initial guesses and work through what the model is telling us:</p>
<ol style="list-style-type: decimal">
<li>Males are heavier than females (what is the difference in the intercepts?)</li>
<li>The effect of height on weight is positive (the slope(s) are positive, not negative)</li>
<li>There might be a difference in slopes - the Male line is steeper.
`</li>
</ol>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_Davis_log)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: log(weight)
##                  Df Sum Sq Mean Sq  F value    Pr(&gt;F)    
## log(height)       1 4.6643  4.6643 357.4735 &lt; 2.2e-16 ***
## sex               1 0.3446  0.3446  26.4115 6.647e-07 ***
## log(height):sex   1 0.0144  0.0144   1.1038    0.2947    
## Residuals       196 2.5574  0.0130                       
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The table tells us that there is no evidence for an interaction. The last line of this table contains the p-value for the interaction. It is testing the null hypothesis that the slopes are the same. We can not reject this null hypothesis. There is no evidence that allowing the slopes for Males and Females be different is supported. That’s the answer to guess 3 above. It is also the answer to our question: does the effect of Height on Weight vary by Sex. Nope.</p>
<p>However, we do detect <em>main effects</em> of height and sex. This means that each of these DOES have an effect - but we say the effects are additive.</p>
<p>Great. What this means is that the data actually conform to picture in the lower left.</p>
<p><img src="images/ANCOVA_1.png" width="644" /></p>
<p>There is a slope associated with Height (we don’t know whether it’s positive or not, but we think it is), and there is an effect of sex (we don’t know whether Males are heavier yet). What we can say, with confidence, is this.</p>
<blockquote>
<p>The effect of height on weight did not vary by sex (F = 1.01, df = 1,196, p = 0.29). The effect of sex (F, df, p) and height (F, df, p) are thus additive on Weight.</p>
</blockquote>
<p>Another way to read this is the following:</p>
<p>When we allow for a common slope associated with logHeight, we capture 4.66 units of variation in weight, which when compared to the 0.013 units of variation left over (residual MSE), is alot. The F is thus BIG and the p-value small. When we allow for an effect of Sex to define different average weights, this too is important as it captures 0.344 units of variation in weight, which comparied to the 0.013 units in the residual, is also big (Big F, small P). However, when we allow for the slopes caused by height to vary with sex, this captures very little variation with respect to the residual variation (0.014 comprared to 0.013) hence a small F and a large P.</p>
</div>
<div id="the-summary-table-and-making-sense-of-the-log-stuff." class="section level3" number="10.3.3">
<h3><span class="header-section-number">10.3.3</span> The summary table and making sense of the log stuff.</h3>
<p>Let’s start investigating the actual details via the <code>summary</code> table:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_Davis_log)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(weight) ~ log(height) * sex, data = Davis)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.29310 -0.06543 -0.00592  0.07420  0.43410 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -5.3202     1.6016  -3.322  0.00107 ** 
## log(height)        1.8329     0.3138   5.841 2.13e-08 ***
## sexM              -2.3724     2.3765  -0.998  0.31936    
## log(height):sexM   0.4852     0.4618   1.051  0.29473    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1142 on 196 degrees of freedom
## Multiple R-squared:  0.6626, Adjusted R-squared:  0.6575 
## F-statistic: 128.3 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This table reports on the <em>treatment contrasts</em> we introduced earlier this semester. Let’s walk through the details.</p>
<p>The first two rows correspond to one of the sexes. Can you identify which one? The hint is looking at the other rows. They have an M after them. M comes after F. So the first two rows correspond to the intercept and slope of the Females.</p>
<p>You may be asking why the intercept is a negative number. A simple look back at the range of the x-axis should answer this… the y intercept occurs at x = 0, right?</p>
<p>You should understand, from the principles of an equation for a line, the following:</p>
<blockquote>
<p>the effect of height on weight for females is <code>log(weightF) = -5.31 + 1.82*log(heightF)</code>.</p>
</blockquote>
<p>OK… let’s interpret what the next two lines mean. The third line is labelled <code>SexM.</code> The fourth is labelled <code>logHeight:SexM</code>. Any guesses as to which is associated with the slope and which the intercept?</p>
<p>One trick, again, is to recognise the syntax -&gt; the presence of the <code>:</code> is indicative of the interaction which is the thing that lets slopes vary. So, <code>SexM</code> is about intercepts and <code>logHeight:SexM</code> is about slopes. But what are they?</p>
<p>Please recall from previous work that treatment contrasts are about DIFFERENCES. Thus, the <code>sexM</code> term is a difference between the female and make intercept and the <code>logHeight:SexM</code> is about the difference between the female and make slopes.</p>
<p>This allows the following maths….</p>
<p><code>log(weightF) = -5.31 + 1.82*log(heightF)</code></p>
<p><code>log(weightM) = (-5.31-2.37) + (1.82+0.48)*(log(heightF))</code></p>
<p>However, we know that the 0.48 increase in the slope is not siginficant, and as a result, the -2.37 increase in the intercept is also not correct.</p>
</div>
<div id="the-equations-supported-by-the-model." class="section level3" number="10.3.4">
<h3><span class="header-section-number">10.3.4</span> The equations supported by the model.</h3>
<p>In order to identify the equations supported by the model, we can refit the model to reflect the ADDITIVE effects only.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb105-1" aria-hidden="true" tabindex="-1"></a>mod_Davis_log2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(weight) <span class="sc">~</span> <span class="fu">log</span>(height) <span class="sc">+</span> sex, <span class="at">data =</span> Davis)</span>
<span id="cb105-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_Davis_log2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(weight) ~ log(height) + sex, data = Davis)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.28714 -0.06906 -0.00978  0.07615  0.43717 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -6.46349    1.17541  -5.499 1.18e-07 ***
## log(height)  2.05688    0.23030   8.931 2.99e-16 ***
## sexM         0.12417    0.02417   5.138 6.66e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1143 on 197 degrees of freedom
## Multiple R-squared:  0.6607, Adjusted R-squared:  0.6573 
## F-statistic: 191.8 on 2 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Right, now we get our expected pattern:</p>
<p><code>log(weightF) = -6.46 + 2.05*log(heightF)</code></p>
<p><code>log(weightM) = (-6.46 + 0.12) + 2.05*log(heightF)</code></p>
<p>We can see the common slope and the slightly higher average weight (0.12 units!) of males.</p>
</div>
<div id="making-even-more-inference-and-drawing-the-picture" class="section level3" number="10.3.5">
<h3><span class="header-section-number">10.3.5</span> Making even more inference and drawing the picture</h3>
<p>OK, lets use some plotting tricks and get a nice picture:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first create a data frame to use that combines the raw data </span></span>
<span id="cb107-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="co"># with the predictions from the model</span></span>
<span id="cb107-3"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb107-3" aria-hidden="true" tabindex="-1"></a><span class="co"># note that the model is the ADDITIVE model, for plotting</span></span>
<span id="cb107-4"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb107-4" aria-hidden="true" tabindex="-1"></a>plotThis <span class="ot">&lt;-</span> Davis <span class="sc">%&gt;%</span> </span>
<span id="cb107-5"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb107-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">preds =</span> <span class="fu">predict</span>(mod_Davis_log2))</span>
<span id="cb107-6"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb107-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-7"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb107-7" aria-hidden="true" tabindex="-1"></a><span class="co"># now, make lines with the model predictions</span></span>
<span id="cb107-8"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb107-8" aria-hidden="true" tabindex="-1"></a><span class="co"># and add the points as the raw data</span></span>
<span id="cb107-9"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb107-9" aria-hidden="true" tabindex="-1"></a><span class="co"># pay attention to where we are using log()!</span></span>
<span id="cb107-10"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb107-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plotThis, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">log</span>(height), <span class="at">y =</span> preds, <span class="at">col =</span> sex))<span class="sc">+</span></span>
<span id="cb107-11"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb107-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb107-12"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb107-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">log</span>(weight)))</span></code></pre></div>
<p><img src="Introduction-to-Experimental-Design-and-Analysis_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>Great. Now we can see that the full model (mod_Davis_log) told us. The lines are parallel. There is no interaction.</p>
<p>In fact, we can do a bit more here.</p>
<p>Remember that the model says</p>
<p>For women log(weight)= -6.46 + 2.05 * log(height)
For men log(weight)= (-6.46 + 0.12) + 2.05 * log(height)</p>
<p>Because we are in log land, we can do some clever maths: We know that</p>
<p><code>log(weight Female) - log(weight Male) = - 0.12</code></p>
<p>(this is the treatment contrast for the intercept). We also know (please memorise) that the difference between logs is equal to the log of the ratio:</p>
<p><code>log(weightF/weightM) = -0.12</code></p>
<p>Finally, we can convert both sides to non-log by exponentiating:</p>
<p><code>exp(log(weightF/weightM)) = exp(-0.12) = 0.88</code></p>
<p>What does this mean? At any given height, female weight is 88% of a makes (12% lower).</p>
<p>Cool! That’s one of the benefits of log-log linear relationships. The ratio of the categories in log-log land directly translates to a percent difference between the groups.</p>
<p>It’s also worth noting that the height slope is ~2, which suggests… yes… because we are in log-land, that weight scales with <span class="math inline">\(height^2\)</span>.</p>
<p>One way to ‘test’ this is to ask whether estimating the log(weight) slope improve the fit of the model compared to fixing it at 2. Here are ways: ‘by hand’ and by a function in the <code>car</code> package.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># by hand</span></span>
<span id="cb108-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="co"># we use the offset function to fix the slope of height at 2</span></span>
<span id="cb108-3"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb108-3" aria-hidden="true" tabindex="-1"></a>mod_Davis_offset <span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="fu">log</span>(weight) <span class="sc">~</span>  sex <span class="sc">+</span> <span class="fu">offset</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">log</span>(height)), <span class="at">data=</span>Davis)</span>
<span id="cb108-4"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb108-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-5"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb108-5" aria-hidden="true" tabindex="-1"></a><span class="co"># then compare it to the model where we estimate it freely.</span></span>
<span id="cb108-6"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb108-6" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_Davis_log2, mod_Davis_offset)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: log(weight) ~ log(height) + sex
## Model 2: log(weight) ~ sex + offset(2 * log(height))
##   Res.Df    RSS Df  Sum of Sq     F Pr(&gt;F)
## 1    197 2.5718                           
## 2    198 2.5726 -1 -0.0007962 0.061 0.8052</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co"># by car package</span></span>
<span id="cb110-2"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb110-2" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">linearHypothesis</span>(mod_Davis_log2, <span class="st">&quot;log(height) = 2&quot;</span>) <span class="co"># the estimate IS 2</span></span></code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## log(height) = 2
## 
## Model 1: restricted model
## Model 2: log(weight) ~ log(height) + sex
## 
##   Res.Df    RSS Df Sum of Sq     F Pr(&gt;F)
## 1    198 2.5726                          
## 2    197 2.5718  1 0.0007962 0.061 0.8052</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb112-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">linearHypothesis</span>(mod_Davis_log2, <span class="st">&quot;log(height) = 0&quot;</span>) <span class="co"># the estimate IS NOT 0.</span></span></code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## log(height) = 0
## 
## Model 1: restricted model
## Model 2: log(weight) ~ log(height) + sex
## 
##   Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)    
## 1    198 3.6131                                 
## 2    197 2.5718  1    1.0413 79.768 2.99e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
</div>
<div id="some-general-principles" class="section level2" number="10.4">
<h2><span class="header-section-number">10.4</span> Some General Principles</h2>
<div id="ancova-always-tests-the-interaction-against-the-additive-model" class="section level3" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> ANCOVA always tests the interaction against the additive model</h3>
<p>This figure highlights the various models and interpretations associated with the pieces of an ANCOVA dataset. This is a way to envision all of the potential linear relationships among the variables that might arise in an experiment with a continuous and categorical explanatory variable.</p>
<p>Note that just because your data looks like a particular pattern doesn’t mean you should use that model. Your statistical model should be driven by your question and original design.</p>
<div class="figure"><span id="fig:unnamed-chunk-60"></span>
<img src="images/GSwithR_Grid.png" alt="From Getting Started with R, 2nd Edition, OUP" width="740" />
<p class="caption">
Figure 10.1: From Getting Started with R, 2nd Edition, OUP
</p>
</div>
<p>For example, if you design a study with an ANCOVA question in mind, you are always starting your analysis with the question of whether the effect of X on Y varies by Z. Thus, ANCOVA always starts with comparing the interaction (model E) against the additive model (model D).</p>
<blockquote>
<p>Proof: If we compare the additive model and the model with the interaction, we are specifically testing for whether allowing the slopes to vary by sex <em>explains additional variation</em> above and beyond the main, additive effects of height and sex. To do this, we use <code>anova()</code> but pass it two models. This does what is called a Liklihood Ratio Test.
Compare the result of the first test to the last line of the second. This proves that when we fit model E, the test for the interaction is a comparison with model D!</p>
</blockquote>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_Davis_log, mod_Davis_log2)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: log(weight) ~ log(height) * sex
## Model 2: log(weight) ~ log(height) + sex
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1    196 2.5574                           
## 2    197 2.5718 -1 -0.014402 1.1038 0.2947</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="introducing-the-ancova-the-analysis-of-covariance.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(mod_Davis_log)</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: log(weight)
##                  Sum Sq  Df F value    Pr(&gt;F)    
## log(height)     1.04135   1 79.8099 3.024e-16 ***
## sex             0.34461   1 26.4115 6.647e-07 ***
## log(height):sex 0.01440   1  1.1038    0.2947    
## Residuals       2.55738 196                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="specifying-models-in-r" class="section level3" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> Specifying models in R</h3>
<p>We can add terms
<code>weight ~ sex + height</code></p>
<p>Have crossed terms
<code>weight ~ sex * height</code> which is <code>weight ~ sex +  height + sex : height</code></p>
<p>Remove terms
<code>weight ~ sex * height – sex : height</code> which is <code>weight~ sex +  height</code></p>
<p>Include all interactions up to order k
<code>weight~ (sex + height + age)^2</code> which is <code>sex + height + age + sex : height + sex : age + age : height</code></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="experimental-design-and-anova-a-summary.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="nonlinearities-polynomials-and-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Introduction to Experimental Design and Analysis.pdf", "Introduction to Experimental Design and Analysis.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
